---
title: "Plot vote shares"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plot Vote Shares}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### plot voteshares on the cantonal level
```{r echo=TRUE, warning=FALSE, message=FALSE}
# installation from CRAN (stable)
# install.packages("swissdd")
# install.packages("dplyr")
# install.packages("RSwissMaps")

# installation from github (ongoing updates)
# devtools::install_github("politanch/swissdd")

library(swissdd)
library(dplyr)
library(RSwissMaps)

#get data from API for the 2014 Swiss immigration initiative (mei)
mei_nat <- get_nationalvotes(votedates="2014-02-09", geolevel = "canton")%>%
  dplyr::filter(id == 5800)%>%
  dplyr::select(canton_id, jaStimmenInProzent)%>%
  mutate(canton_id=as.numeric(canton_id))

#plot
can.plot(mei_nat$canton_id, mei_nat$jaStimmenInProzent, 2016,
         title = "2014 Swiss immigration initiative ",
         subtitle = "Swiss Cantons, 2016", 
         caption = "Data:swissdd/FSO\nPlot:RSwissMaps", dpi=300)
```


### plot voteshares on the municipal level

```{r echo=TRUE, warning=FALSE, message=FALSE}
#get data from API for the 2014 Swiss immigration initiative (mei)
mei_mun <- get_nationalvotes(votedates="2014-02-09", geolevel = "municipality")%>%
  dplyr::filter(id == 5800)%>%
  dplyr::select(mun_id, jaStimmenInProzent)%>%
  mutate(mun_id=as.numeric(mun_id))

mun.plot(mei_mun$mun_id, mei_mun$jaStimmenInProzent, 2016,
         color_continuous = c("#c7e9c0", "#006d2c"),
         boundaries_size = 0.2,
         title = "2014 Swiss immigration initiative ",
         subtitle = "Swiss Municipalities, 2016", 
         caption = "Data:swissdd/FSO\nPlot:RSwissMaps")
```

